config/routes.rb
Tuhao::Application.routes.draw do
  
  root 'welcome#index'
  
  match '/howto',               to: 'welcome#howto',        via: 'get'
  match '/login',               to: 'sessions#new',         via: 'get'
  match '/login',               to: 'sessions#create',      via: 'post'
  match '/logout',              to: 'sessions#destroy',     via: 'get'
  match '/survey',              to: 'survey#survey',        via: 'get'
  match '/profile',             to: 'users#profile',        via: 'get'
  match '/update_user_profile', to: 'users#edit_profile',   via: 'get'
  match '/update_user_password',to: 'users#edit_password',  via: 'get'
  match '/update_pet_profile/:id',  to: 'pets#edit_profile',    via: 'get'
  match '/survey',              to: 'surveyresults#create', via: 'post'
  match '/explore',             to: 'users#explore',        via: 'get'
  
  resources :users
  resources :surveyresults
  resources :sessions
  resources :pets
  resources :posts

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :pets
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize, :except => ["new", "create"]

	# GET /posts
  	# GET /posts.json
  	def index
    	@users = User.all
  	end

	# GET /posts/new
	def new
		@user = User.new
	end

	# POST
	def create
    @user = User.new(user_params)

	    respond_to do |format|
	    	if @user.save
	    		format.html { redirect_to login_path , flash:{success: 'User was successfully created, please log in.'} }
	      	else
	        	format.html { render action: 'new', flash:{alert: "Unable to create such user."} }
	        	format.json { render json: @user.errors, status: :unprocessable_entity }
	      	end
	    end
  	end

  	# GET /books/1/edit
    def edit_profile
    	@user = User.find(current_user.id)
    end
    def edit_password
    	@user = User.find(current_user.id)
    end

  	# PATCH/PUT /users/1
  	# PATCH/PUT /users/1.json
	def update
		@user = User.find(current_user.id)
		respond_to do |format|
		  if @user.update(user_params)
		    format.html { redirect_to profile_path, flash: {success: 'User was successfully updated.' } }
		    format.json { head :no_content }
		  else
		    format.html { redirect_to profile_path, flash: {alert: 'Unable to update password.' } }
		    format.json { render json: @user.errors, status: :unprocessable_entity }
		  end
		end
	end

  	def signin
  	end

  	def explore
    end
  	

	def show
		@user = User.find(params[:id])
  	end	

  	
  	private
  		def user_params
    		params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  		end
  		
  		def set_book
      		@user = User.find(params[:id])
    	end
    	
    	# Use callbacks to share common setup or constraints between actions.
    	def set_post
      		@user = User.find(params[:id])
    	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<div id="main-body" class="regular_ver imageBG-others">
    <div class="container">
	<!-- edit form column -->
     	<h1 class="">Edit Guarantor Info</h1>

        <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
        
            <div class="form-group">
                <label class="col-lg-3 control-label">First name:</label>
                <div class="col-lg-8">
                    <%= f.text_field :firstname, :placeholder => "First Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Last name:</label>
                <div class="col-lg-8">
                    <%= f.text_field :lastname, :placeholder => "Last Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Email:</label>
                <div class="col-lg-8">
                    <%= f.text_field :email, :placeholder => "Email", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Password:</label>
                <div class="col-md-8">
                    <%= f.password_field :password, :placeholder => "New Password", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Confirm password:</label>
                <div class="col-md-8">
                    <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-8">
                    <input class="btn btn-primary" value="Save Changes" type="submit"> <span class=""></span>

                    <input class="btn btn-default" value="Cancel" type="reset">
                </div>
            </div>
        <% end %>
    </div>
    </div>
</div>
<hr class="">

app/views/users/edit_password.html.erb
<div id="main-body" class="regular_ver imageBG-others">
    <div class="container">
	<!-- edit form column -->
     	<h1 class="">Edit Guarantor Password</h1>

        <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
            <div class="form-group">
                <label class="col-md-3 control-label">Password:</label>
                <div class="col-md-8">
                    <%= f.password_field :password, :placeholder => "New Password", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Confirm password:</label>
                <div class="col-md-8">
                    <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-8">
                    <input class="btn btn-primary" value="Save Changes" type="submit"> <span class=""></span>

                    <input class="btn btn-default" value="Cancel" type="reset">
                </div>
            </div>
        <% end %>
    </div>
    </div>
</div>
<hr class="">

app/views/users/edit_profile.html.erb
<div id="main-body" class="regular_ver imageBG-others">
    <div class="container">
	<!-- edit form column -->
     	<h1 class="">Edit Guarantor Info</h1>

        <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
        
            <div class="form-group">
                <label class="col-lg-3 control-label">First name:</label>
                <div class="col-lg-8">
                    <%= f.text_field :firstname, :placeholder => "First Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Last name:</label>
                <div class="col-lg-8">
                    <%= f.text_field :lastname, :placeholder => "Last Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Email:</label>
                <div class="col-lg-8">
                    <%= f.text_field :email, :placeholder => "Email", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-8">
                    <input class="btn btn-primary" value="Save Changes" type="submit"> <span class=""></span>

                    <input class="btn btn-default" value="Cancel" type="reset">
                </div>
            </div>
        <% end %>
    </div>
    </div>
</div>
<hr class="">

app/views/users/explore.html.erb
<div id="main-body" class="regular_ver imageBG-others">
  <div class="container">
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
      <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
      </div>

      <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum.ris sit amet orci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliqur mauris sit amet orci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquam porauris sit amet orci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttt amet orci. </p>
      </div>

            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquam p sit amet orci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquaor mauris sit amet orci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Alrci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis fermentum. Aliquam ci. </p>
      </div>
            <div class="box col2">
        <p>Donec nec justo eget felis facilisis auris sit amet orci. </p>
      </div>
      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>

      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
            <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>

      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
      <div class="box col2">
        <p>
          <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="http://farm4.static.flickr.com/3008/3319714470_c05a5cb5a8_m.jpg" alt="Whitlow's on Wilson" /></a>
        </p>
      </div>
      ...
    </div>
  </div>
</div>
<script>
$(function(){
  $('#masonry-container').masonry({
    itemSelector: '.box',
    columnWidth: 10,
    isAnimated: !Modernizr.csstransitions,
    isFitWidth: true
  });

});
</script>

app/views/users/new.html.erb
<div id="main-body" class=" center_ver container center imageBG-others">
    <div class="well well-lg center" style="width: 50%; margin: auto">
        <legend><i class="glyphicon glyphicon-user"></i> Sign up!</legend>
        <%= form_for @user, html: {class: "form"} do |f| %>
            <div class="row">
                <div class="col-xs-6 col-md-6">
                    <%= f.text_field :firstname, :placeholder => "First Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
                <div class="col-xs-6 col-md-6">
                    <%= f.text_field :lastname, :placeholder => "Last Name", class: "form-control", :autofocus => true, :required => true %>
                </div>
            </div>
            <br/>
            <%= f.text_field :email, :placeholder => "Email", class: "form-control", :autofocus => true, :required => true %>
            <br/>
            <%= f.password_field :password, :placeholder => "New Password", class: "form-control", :autofocus => true, :required => true %>
            <br/>
            <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", class: "form-control", :autofocus => true, :required => true %>
            <br/>
            <button class="btn btn-md btn-primary btn-block" type="submit">
            Sign up</button>
        <% end %>
    </div>
</div>

app/views/users/profile.html.erb
<div id="main-body" class="regular_ver imageBG-others">
    <div class="container">

        <% if flash[:notice] %>
            <div class="alert alert-dismissible alert-info" role="alert"> 
                <button type="button" class="close" data-dismiss="alert">×</button>
                <%= flash[:notice] %> 
            </div>
        <% elsif flash[:alert] %>
            <div class="alert alert-dismissible alert-danger" role="alert"> 
                <button type="button" class="close" data-dismiss="alert">×</button>
                <%= flash[:alert] %> 
            </div>
        <% elsif flash[:warning] %>
            <div class="alert alert-dismissible alert-warning" role="alert"> 
                <button type="button" class="close" data-dismiss="alert">×</button>
                <%= flash[:warning] %> 
            </div>
        <% elsif flash[:success] %>
            <div class="alert alert-dismissible alert-success" role="alert"> 
                <button type="button" class="close" data-dismiss="alert">×</button>
                <%= flash[:success] %> 
            </div>
        <% end %>
        <div class="row">
            <div class="col-md-3">
                <h1 class=""><span class="glyphicon glyphicon-user"></span> Guarantor </h1>
                <hr class="">

                <h4><%= current_user.firstname %> <%= current_user.lastname %></h4>
                <h4><%= current_user.email %></h4>
                <%= link_to "Update Profile", update_user_profile_path , class: "btn btn-xs btn-primary" %>
                <%= link_to "Change Password", update_user_password_path , class: "btn btn-xs btn-primary" %>
                <%= link_to "Add a pet", new_pet_path , class: "btn btn-xs btn-primary" %>

            </div>
            <div class="col-md-1">
                <div class="vr">
                </div>
            </div>
            <div class="col-md-8">
                <h1 class=""><span class="glyphicon glyphicon-heart"></span> My Pets</h1>

                <% current_user.pets.each do |f| %>
                <hr class="">

                <div class="row">
                    <div class="col-md-4">
                        <div class="text-center">
                            <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                            <br/>
                            <br/>
                            <input class="file" type="file">
                        </div>
                    </div>
                    <!-- detail column -->
                    <div class="col-md-6">
                        <form class="form-horizontal" role="form">
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Name:</label>
                                <div class="col-lg-8">
                                    <label class="control-label"><%= f.name %></label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Birthday:</label>
                                <div class="col-lg-8">
                                    <label class="control-label"><%= f.birthday %></label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Gender:</label>
                                <div class="col-lg-8">
                                    <label class="control-label">Female</label>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-1">
                        <%= link_to "Edit", "update_pet_profile/" + f.id.to_s , class: "btn btn-xs btn-primary" %>
                    </div>
                </div>
                <% end %>   
            </div>
        </div>      
        <br/>
    </div>
</div>

app/views/users/show.html.erb
<div id="main-body" class="regular_ver center imageBG-others">
	<div class="container">
    <div class="">
        <h1 id="timeline">Timeline</h1>
    </div>
    <ul class="timeline">
        <li>
          <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">First Posts</h4>
              <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 11 hours ago via Tuhao</small></p>
            </div>
            <div class="timeline-body">
              <p>hello</p>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
              <p>Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Interagi no mé, cursus quis, vehicula ac nisi. Aenean vel dui dui. Nullam leo erat, aliquet quis tempus a, posuere ut mi. Ut scelerisque neque et turpis posuere pulvinar pellentesque nibh ullamcorper. Pharetra in mattis molestie, volutpat elementum justo. Aenean ut ante turpis. Pellentesque laoreet mé vel lectus scelerisque interdum cursus velit auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac mauris lectus, non scelerisque augue. Aenean justo massa.</p>
            </div>
          </div>
        </li>
        <li>
          <div class="timeline-badge danger"><i class="glyphicon glyphicon-credit-card"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>
        <li>
          <div class="timeline-badge info"><i class="glyphicon glyphicon-floppy-disk"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
              <hr>
              <div class="btn-group">
                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                  <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>
    </ul>
</div>
  	<div class="container">
		<% if flash[:notice] %>
        	<div class="alert alert-dismissible alert-info" role="alert"> <%= flash[:notice] %> </div>
        <% elsif flash[:alert] %>
        	<div class="alert alert-dismissible alert-danger" role="alert"> <%= flash[:alert] %> </div>
        <% elsif flash[:warning] %>
        	<div class="alert alert-dismissible alert-warning" role="alert"> <%= flash[:warning] %> </div>
        <% elsif flash[:success] %>
        	<div class="alert alert-dismissible alert-success" role="alert"> <%= flash[:success] %> </div>
      	<% end %>
		<h3>
	  		<strong>FirstName: </strong><%= @user.firstname %>
		</h3>

		<h3>
	  		<strong>LastName: </strong><%= @user.lastname %>
		</h3>
		<h3>
	  		<strong>Email: </strong><%= @user.email %>
		</h3>
	</div>
</div>