config/routes.rb
Tuhao::Application.routes.draw do
  
  root 'welcome#index'
  
  match '/howto',               to: 'welcome#howto',        via: 'get'
  match '/login',               to: 'sessions#new',         via: 'get'
  match '/login',               to: 'sessions#create',      via: 'post'
  match '/logout',              to: 'sessions#destroy',     via: 'get'
  match '/survey',              to: 'survey#survey',        via: 'get'
  match '/profile',             to: 'users#profile',        via: 'get'
  match '/update_user_profile', to: 'users#edit_profile',   via: 'get'
  match '/update_user_password',to: 'users#edit_password',  via: 'get'
  match '/update_pet_profile/:id',  to: 'pets#edit_profile',    via: 'get'
  match '/survey',              to: 'surveyresults#create', via: 'post'
  match '/explore',             to: 'users#explore',        via: 'get'
  
  resources :users
  resources :surveyresults
  resources :sessions
  resources :pets
  resources :posts

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/surveyresult.rb
class Surveyresult < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :pets
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	before_filter :authorize, :except => ["new", "create"]

	# GET /posts
  	# GET /posts.json
  	def index
    	@pets = Pet.all
  	end

	# GET /posts/new
	def new
		@pet = Pet.new
	end

	def edit_profile
		# params[:id] is the pet id passed in url
		if current_user.pets.find_by_id(params[:id]) != nil then
     		@pet = current_user.pets.find(params[:id])
     	else
     		respond_to do |format|
     			format.html { redirect_to profile_path , flash:{alert: "Could not find the pet."} }
     		end
     	end  		
    end

	# POST
	def create
	params[:pet][:user_id] = current_user.id
    @pet = Pet.new(pet_params)
    
	    respond_to do |format|
	    	if @pet.save
	    		format.html { redirect_to profile_path , flash:{success: 'Pet was successfully created.'} }
	      	else
	        	format.html { render action: 'new', flash:{alert: "Unable to create such pet."} }
	        	format.json { render json: @pet.errors, status: :unprocessable_entity }
	      	end
	    end
  	end

  	def update
		@pet = current_user.pets.find_by_id(params[:id])
		respond_to do |format|
		  if @pet.update(pet_params)
		    format.html { redirect_to profile_path, flash: {success: 'Pet was successfully updated.' } }
		    format.json { head :no_content }
		  else
		    format.html { redirect_to profile_path, flash: {alert: 'Unable to update pet profile.' } }
		    format.json { render json: @pet.errors, status: :unprocessable_entity }
		  end
		end
	end

  	private
  		def pet_params
    		params.require(:pet).permit(:name, :birthday, :gender, :category, :breed, :user_id)
  		end
  		
  		def set_book
      		@pet = Pet.find(params[:id])
    	end
    	
    	# Use callbacks to share common setup or constraints between actions.
    	def set_post
      		@pet = Pet.find(params[:id])
    	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	# GET /histories
  	# GET /histories.json
	def index
    	@posts = Post.all

	    respond_to do |format|
	    format.html # show.html.erb
	    format.json { render json: json_out = {"timeline"=>
	    	{
	        	"headline"=>"Welcome to my family!",
	          	"type"=>"default",
	          	"text"=>"<p>Intro body text goes here, some HTML is ok</p>",
	          	"asset"=> {
	          	"media"=>"http://www.exglam.com/wp-content/uploads/2013/02/Kajal-agarwal-in-Blue-and-white-Fade-Short-with-white-Top-and-a-Blue-bow-in-hair.jpg",
	          	"credit"=>"Credit Name Goes Here",
	          	"caption"=>"Caption text goes here"
	        	},

	        	"date"=> @posts.map { |timeline| {"startDate" => timeline.created_at.strftime("%Y,%m,%d, %H, %M, %S"), "headline" => timeline.headline,"text" => timeline.content, "asset" => {"media" => timeline.media}}},


	          	"era"=> [
	            {
	          	"startDate"=>"2011,12,10",
	          	"endDate"=>"2011,12,11",
	          	"headline"=>"Headline Goes Here",
	          	"text"=>"<p>Body text goes here, some HTML is OK</p>",
	          	"tag"=>"This is Optional"
	        	}

	        	]
	        }
	      } 
	  	}
	    end
	end

	# GET /histories/1
	# GET /histories/1.json
	def show
	end

	# GET /histories/new
	def new
		@post = Post.new
	end

	# GET /histories/1/edit
	def edit
	end

	# POST /histories
	# POST /histories.json
	def create
	    @post = Post.new(post_params)

	    respond_to do |format|
	      if @post.save
	        format.html { redirect_to @post, notice: 'History was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @post }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # PATCH/PUT /histories/1
	  # PATCH/PUT /histories/1.json
	  def update
	    respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to @post, notice: 'History was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /histories/1
	  # DELETE /histories/1.json
	  def destroy
	    @post.destroy
	    respond_to do |format|
	      format.html { redirect_to posts_url }
	      format.json { head :no_content }
	    end
	  end

	  private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_post
	    @post = Post.find(params[:id])
	  end

	  # Never trust parameters from the scary internet, only allow the white list through.
	  def post_params
	    params.require(:post).permit(:startdate, :enddate, :content, :headline, :media, :mediacaption, :mediacredit)
	  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
	


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize, :except => ["new", "create"]

	# GET /posts
  	# GET /posts.json
  	def index
    	@users = User.all
  	end

	# GET /posts/new
	def new
		@user = User.new
	end

	# POST
	def create
    @user = User.new(user_params)

	    respond_to do |format|
	    	if @user.save
	    		format.html { redirect_to login_path , flash:{success: 'User was successfully created, please log in.'} }
	      	else
	        	format.html { render action: 'new', flash:{alert: "Unable to create such user."} }
	        	format.json { render json: @user.errors, status: :unprocessable_entity }
	      	end
	    end
  	end

  	# GET /books/1/edit
    def edit_profile
    	@user = User.find(current_user.id)
    end
    def edit_password
    	@user = User.find(current_user.id)
    end

  	# PATCH/PUT /users/1
  	# PATCH/PUT /users/1.json
	def update
		@user = User.find(current_user.id)
		respond_to do |format|
		  if @user.update(user_params)
		    format.html { redirect_to profile_path, flash: {success: 'User was successfully updated.' } }
		    format.json { head :no_content }
		  else
		    format.html { redirect_to profile_path, flash: {alert: 'Unable to update password.' } }
		    format.json { render json: @user.errors, status: :unprocessable_entity }
		  end
		end
	end

  	def signin
  	end

  	def explore
    end
  	

	def show
		@user = User.find(params[:id])
  	end	

  	
  	private
  		def user_params
    		params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  		end
  		
  		def set_book
      		@user = User.find(params[:id])
    	end
    	
    	# Use callbacks to share common setup or constraints between actions.
    	def set_post
      		@user = User.find(params[:id])
    	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def survey
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/surveyresults_helper.rb
module SurveyresultsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div id="footer" class="imageBG-others">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
          <p class="copyright">Copyright &copy; 2015 - TreatsBowl.com</p>
      </div>
      <div class="col-md-3 ">
		<p>
			<a href="#"><i class="fa fa-facebook-square fa-2x"  ></i> </a>  
			<a href="#"><i class="fa fa-twitter-square fa-2x"  ></i> </a>  
			<a href="#"><i class="fa fa-linkedin-square fa-2x"  ></i> </a>  
			<a href="#"><i class="fa fa-google-plus-square fa-2x"  ></i> </a>  
		</p>
    </div>    
  </div>  
</div>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "TreatsBowl", root_path, class: "navbar-brand" %>
		</div>
		<div class="navbar-collapse collapse in">
			<% if current_user %>
				<ul class="nav navbar-nav">
	        		<li class="dropdown">
	          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"> Menu <span class="caret"></span></a>
	          			<ul class="dropdown-menu" role="menu">
	            			<li><a href="#">Friend Feeds</a></li>
	            			<li><%= link_to "My Family", user_path(current_user[:id]) %></li>
	            			<li><%= link_to "Explore", explore_path %></li>
	            			<li class="divider"></li>
	            			<li><a href="#">Extended link</a></li>
	          			</ul>
	        		</li>
	      		</ul>
	      		<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "HowTo", howto_path %></li>
  						<li><a href="#">Messages <span class="badge">3</span></a></li>
	  					<li class="dropdown">
		          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"> <%=current_user.firstname%> <%=current_user.lastname%> <span class="caret"></span></a>
		          			<ul class="dropdown-menu" role="menu">
		          				<li><%= link_to "Profile", profile_path %></li>
		            			<li><%= link_to "Logout", logout_path %></li>
		          			</ul>
		        		</li>
					
				</ul>
	      	<% else %>
	      		<ul class="nav navbar-nav navbar-right">

					<% if current_user %>
						<li><%= link_to "HowTo", "#" %></li>
						<li><%= link_to "Logout", "#" %></li>
	  				<% else %>
	  					<li><%= link_to "HowTo", "#" %></li>
						<li><%= link_to "Login", "#" %></li>
					<% end %>
					
				</ul>
	      	<% end %>
			
		</div><!--/.nav-collapse -->
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    <link href="/assets/application.css.sass" media="all" rel="stylesheet" />
    <%= javascript_include_tag "application" %>
    <title>TreatsBowl - Online social network for pets.</title>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60995641-1', 'auto');
  ga('send', 'pageview');

</script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!-- yield main body -->    
    <%= yield %>
    <%= render 'layouts/footer' %>
    

    <% if Rails.application.enable_debug == 1 then %>
      <%=  
      if Rails.env.development?
        debug(params)
      end %>
      <%=  
      if Rails.env.development?
        debug(current_user)
      end %>
      <%=  
      if Rails.env.development?
        if (current_user != nil) then
          debug(current_user.pets)
        end
      end %>
      <%=  
      if Rails.env.development?
        
          debug(@posts)
        
      end %>
      <%=  
      if Rails.env.development?
        debug(flash[:notice])
      end %>
      <%=  
      if Rails.env.development?
        debug(flash[:alert])
      end %>

      <%=  
      if Rails.env.development?
        debug(flash[:warning])
      end %>

      <%=  
      if Rails.env.development?
        debug(flash[:success])
      end %>
    <% end %>
  </body>
</html>